name: CoHack Journey
on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GH Actions Session"

      - name: Checkout Files
        uses: actions/checkout@v6

      - name: Run Shell Script
        run: |
          chmod +x scripts/greet.sh
          ./scripts/greet.sh
